project:
  type: website

  # render all posts except those in folders with "draft" in the name
  render:
    - index.qmd
    - posts/**
  resources:
    - "!posts/*draft*/**"

website:
  title: "Andrew G. Roberts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
